---
- name: VAULT | Download & unzip vault archive
  unarchive:
    src: "{{ vault_download_url }}"
    remote_src: true
    dest: /usr/local/bin/
    mode: 0555
    owner: root
    group: root
  become: true
