---
- name: VAULT | Install unzip
  apt:
    name: unzip
    state: present
    update_cache: true
  become: true
  when:
    - ansible_os_family == "Debian"

- name: VAGRANT | Install unzip
  yum:
    name: unzip
    state: present
    update_cache: true
  become: true
  when:
    - ansible_os_family == "RedHat"

- name: VAULT | Download & unzip vault archive
  unarchive:
    src: "{{ vault_download_url }}"
    remote_src: true
    dest: /usr/local/bin/
    mode: 0555
    owner: root
    group: root
  become: true
